// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// bsItemDao is the data access object for the table hg_bs_item.
// You can define custom methods on it to extend its functionality as needed.
type bsItemDao struct {
	*internal.BsItemDao
}

var (
	// BsItem is a globally accessible object for table hg_bs_item operations.
	BsItem = bsItemDao{internal.NewBsItemDao()}
)

// Add your custom methods and functionality below.
