// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// bsReportDetailDao is the data access object for the table hg_bs_report_detail.
// You can define custom methods on it to extend its functionality as needed.
type bsReportDetailDao struct {
	*internal.BsReportDetailDao
}

var (
	// BsReportDetail is a globally accessible object for table hg_bs_report_detail operations.
	BsReportDetail = bsReportDetailDao{internal.NewBsReportDetailDao()}
)

// Add your custom methods and functionality below.
