// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// bsServiceDao is the data access object for the table hg_bs_service.
// You can define custom methods on it to extend its functionality as needed.
type bsServiceDao struct {
	*internal.BsServiceDao
}

var (
	// BsService is a globally accessible object for table hg_bs_service operations.
	BsService = bsServiceDao{internal.NewBsServiceDao()}
)

// Add your custom methods and functionality below.
