// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// bsStackLogDao is the data access object for the table hg_bs_stack_log.
// You can define custom methods on it to extend its functionality as needed.
type bsStackLogDao struct {
	*internal.BsStackLogDao
}

var (
	// BsStackLog is a globally accessible object for table hg_bs_stack_log operations.
	BsStackLog = bsStackLogDao{internal.NewBsStackLogDao()}
)

// Add your custom methods and functionality below.
