// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// bsWorkOrderDao is the data access object for the table hg_bs_work_order.
// You can define custom methods on it to extend its functionality as needed.
type bsWorkOrderDao struct {
	*internal.BsWorkOrderDao
}

var (
	// BsWorkOrder is a globally accessible object for table hg_bs_work_order operations.
	BsWorkOrder = bsWorkOrderDao{internal.NewBsWorkOrderDao()}
)

// Add your custom methods and functionality below.
